language: node_js
node_js:
  - '8'
install:
  - npm install
  - npm install -g lerna@2.0.0
  - lerna bootstrap
script:
  - lerna run lint --parallel
  - lerna run test:coverage --parallel
  - lerna run build:cjs --parallel
  - lerna run build:es --parallel
git:
  depth: 10
notifications:
  email:
    on_failure: always
    on_success: never
